### ISSUE TITLE
Not compatible with 1.10?

### ISSUE THREAD

**Issue by Dick-Kerman** [linuxgurugamer/EngineLightRelit#12]
Hey, I'm getting an error message on loading saying EngineLightRelit.dll is not compatible with KSP version. I'm not sure if I'm doing something wrong but the download link I used said it was for the current version of the game.
![Screen Shot 2020-09-11 at 12 19 54 PM](https://user-images.githubusercontent.com/71148489/92958556-6c449000-f438-11ea-8911-95b65daa0d77.png)

**Comment by linuxgurugamer** [comment]
First, this is not an issue, it's a support question, as such, you should post these messages on the forum, where others besides myself can answer.
Second, it's a warning only, you can ignore it

**Comment by Dick-Kerman** [comment]
I appreciate you answering me so quickly. Sorry, its so hard to tell what is what on all these forums, so much is outdated, duplicated, and no longer supported that I really dont know where to go for what.That being said... it just stalls at the loading screen with that phrase, the game won't load any further from that point. Thats why I reported it as a bug. Any ideas?

**Comment by linuxgurugamer** [comment]
All of my mods have their own thread, for this one, it is:
https://forum.kerbalspaceprogram.com/index.php?/topic/182906-19x-engine-lighting-relit/

Before you post, read this:
Read this BEFORE asking for support: http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/

You need to get a log file, at a minimum
