### ISSUE TITLE
SSTU Solid Rocket Boosters Produce Light Before Ignited

### ISSUE THREAD

**Issue by Joker58th** [linuxgurugamer/EngineLightRelit#5]
Stock engines work fine, SSTU liquid engines work fine (those I tested), both solids show the issue.

KSP 1.7.1 Vanilla
SSTU-0.11.47.159 with dependencies

[output_log.txt](https://github.com/linuxgurugamer/EngineLightRelit/files/3302562/output_log.txt)

![SSTU Booster Lighting](https://user-images.githubusercontent.com/32574965/59703197-5dd0df80-91c7-11e9-8337-9c83a54c9817.PNG)

![SSTU Mods List](https://user-images.githubusercontent.com/32574965/59703210-63c6c080-91c7-11e9-9d1e-0f31ed9076da.PNG)

**Comment by linuxgurugamer** [comment]
Does this happen when you remove the textures unlimited?

**Comment by Joker58th** [comment]
Well, it was very fun to try and put on an invisible part but yes, it still happens.

![SSTU Booster Lighting 3](https://user-images.githubusercontent.com/32574965/59706684-ef901b00-91ce-11e9-9a76-f332a79a9551.PNG)

VAB looks like this without TU.  SSTU parts don't show up.
![SSTU Booster Lighting 4](https://user-images.githubusercontent.com/32574965/59706744-1c443280-91cf-11e9-91b6-d1890f466b5d.PNG)

**Comment by linuxgurugamer** [comment]
I saw it, but have no idea, have posted in the SSTU thread for  help

**Comment by Joker58th** [comment]
Thanks for the update LGG, looks the lighting is still there but it does look dimmer.

![EngineLight1](https://user-images.githubusercontent.com/32574965/60149803-f22cda80-97a3-11e9-9f57-e7729d50d250.PNG)
