### ISSUE TITLE
1.6.1.1: TypeLoadException: Could not load type 'ModuleDecouplerBase' from assembly 'EngineLightRelit'.

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/EngineLightRelit#6]
Spams like hell.

Log:
https://www.dropbox.com/s/tyc1cc9w1jn34re/output_log.txt%20and%20stuff%202019-06-26-01.zip?dl=1

**Comment by linuxgurugamer** [comment]
Looks like you have the 1.7.1 version of the mod loaded in 1.6.1.  I'm not sure that's an issue, but it wouldn't hurt to try downloading the 1.6.1 version of the mod from Github and trying that out

**Comment by Gordon-Dry** [comment]
It should has been the 1.6.1 version because after file comparision I have seen that the dll differs.
(In some of your releases only the .version file differs)

I will try again to be sure.

**Comment by Gordon-Dry** [comment]
Yeah, you are right.
